### ISSUE TITLE
visible markup on PyPI page

### ISSUE THREAD

**Issue by TomRoche** [mgedmin/restview#32] opened 2015-06-04 17:39 UTC
Just now I browsed to https://pypi.python.org/pypi/restview#synopsis where I am seeing lots of `<kbd>` and `<var>` tags (and their closures) that I suspect should not be world-visible.

**Comment by mgedmin** [comment] 2015-06-05 08:36
Thank you for letting me know!

(Looks like a recent regression in PyPI.)

**Comment by mgedmin** [comment] 2015-06-05 08:50
The ReST source for this is a perfectly cromulent [option list](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#option-lists):

```rest
Usage: ``restview [options] filename-or-directory [...]``

-h, --help            show this help message and exit
-l PORT, --listen=PORT
                      listen on a given port (or interface:port, e.g.
                      \*:8080) [default: random port on localhost]
...
```

It looks like PyPI (and Warehouse) are doing some additional HTML sanitization that forgot about the existence of `<kbd>` tags that docutils uses to render these (and *why* does docutils use those?  I don't know! everything is terrible!).

**Comment by mgedmin** [comment] 2015-06-05 08:50
I cannot reproduce locally by feeding my README.rst into https://github.com/pypa/readme

**Comment by mgedmin** [comment] 2015-06-05 09:09
Filed https://github.com/pypa/warehouse/issues/533

(PyPI's bugs are not tracked on GitHub, so I haven't filed a PyPI bug separately.)

**Comment by mgedmin** [comment] 2015-07-16 08:59
Incidentally, `restview --pypi-strict` itself doesn't show this, which means it's not as accurate as it could be.  AFAIU warehouse is performing an additional clean step that restview isn't.

**Comment by mgedmin** [comment] 2015-07-16 09:27
Here's how [warehouse does the rendering](https://github.com/pypa/warehouse/blob/232444e102ac6dca4010ed22f229d1f927d335e4/warehouse/filters.py#L39-L74):
```python
    value, rendered = readme.rst.render(value)
    if not rendered:
        value = value.replace("\n", "<br>\n")
```
Here's how [restview does the rendering](https://github.com/mgedmin/restview/blob/master/src/restview/restviewhttp.py#L446-L481) (ignoring the error-handling case):
```python
            docutils.core.publish_string(rest_input, writer=writer,
                                         source_path=filename,
                                         settings_overrides=settings_overrides)
            if self.pypi_strict:
                writer.fragment = readme.rst.clean(''.join(writer.fragment))
                writer.output = writer.apply_template()
            html = writer.output
```
To see the difference we need to dive into [readme.rst.render](https://github.com/mgedmin/restview/blob/master/src/restview/restviewhttp.py#L446-L481):
```python
        parts = publish_parts(raw, writer=writer, settings_overrides=settings)
        rendered = parts.get("fragment")
    ...
    return clean(rendered or raw), bool(rendered)
```

So, uh, I don't know what could be different.  It's the `clean()` call that escapes those `<kbd>`s, right?

**Comment by mgedmin** [comment] 2015-07-16 10:00
Ok, now I can reproduce this with `restview --long`.  Side issues being taken care of, now all I need to do is wait for https://github.com/pypa/readme/pull/32 to be merged and then deployed on PyPI and Warehouse.

**Closed** 2015-09-19 07:31 UTC
Labels: waiting-for-upstream
