### ISSUE TITLE
Restview command doesn't work

### ISSUE THREAD

**Issue by 707** [mgedmin/restview#34] opened 2015-08-29 06:08 UTC
OSX Yosemite:
After installing using pip, this error shows for all commands

Crysp-Mac:~ Crysp$ restview -h
Traceback (most recent call last):
  File "/usr/local/bin/restview", line 7, in <module>
    from restview.restviewhttp import main
  File "/usr/local/lib/python2.7/site-packages/restview/restviewhttp.py", line 56, in <module>
    import docutils.core
  File "/usr/local/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File "/usr/local/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "/usr/local/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/usr/local/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/usr/local/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by mgedmin** [comment] 2015-08-31 06:55
Whoa, your system seems to be misconfigured in an interesting way, if `locale.getdefaultlocale()` is raising a ValueError.  I don't see how `restview` can do anything to work around this, since the error occurs while importing docutils.

I'm not sure I can help you figure this out, since I don't use a Mac myself.  Assuming it's sufficiently Linux-like, you may want to try running these commands in shell, in order to try to determine the cause:
```
$ locale charmap
$ locale
```

I'm closing the issue now (since it's not a bug in restview), but I'll try to help you here if you comment with more information.

**Closed by mgedmin** 2015-08-31 06:55 UTC

**Comment by 707** [comment] 2015-09-25 23:36
This is what i get:

Crysp-Mac:~ Crysp$ locale charmap
UTF-8
Crysp-Mac:~ Crysp$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by mgedmin** [comment] 2015-09-28 06:06
"UTF-8" is not a valid locale name.  Can you find where LC_CTYPE is being set (~/.profile?  ~/.bashrc?) and change it to "C.UTF-8", or "en_US.UTF-8", or any valid locale of your choice?

I'm quite surprised that 'locale charmap' outputs UTF-8 in this situation, but I'm not familiar with Mac OS X.  Maybe UTF-8 is their fallback charset?
